SWEP.Base = "mcv_flamethrower"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_m9a1.txt

// Names and basic information
SWEP.PrintName = "M9A1 Flamethrower"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "United States of America"
SWEP.SubCategory = "Flamethrowers"

SWEP.Slot = 3

SWEP.ViewModel = "models/weapons/mcv/v_m9a1.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_m9a1.mdl"
SWEP.MovementPoseWalk = 80
SWEP.MovementPoseSprint = 160
SWEP.MovementPoseSighted = 80

SWEP.DamageGeneric = 15
SWEP.FireRate = 600

SWEP.SoundFireStart = "MCV_Weapon_M9A1.Primary_Fire_Start"
SWEP.SoundFireLoop = "MCV_Weapon_M9A1.Primary_Fire_Loop"
SWEP.SoundFireStop = "MCV_Weapon_M9A1.Primary_Fire_Stop"

SWEP.IronsightPos = Vector(0, -4, 0) -- TODO tune
SWEP.IronsightAng = Angle(0, 0, 0) -- TODO tune

SWEP.Primary.Ammo = "mcv_flamethrower_fuel"
SWEP.Primary.ClipSize = -1
SWEP.Primary.DefaultClip = 100

SWEP.WeaponWeight = 12
