SWEP.Base = "mcv_placeable"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_c4.txt

// Names and basic information
SWEP.PrintName = "C4"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "United States of America"
SWEP.SubCategory = "Explosives"

SWEP.Slot = 4

SWEP.ViewModel = "models/weapons/mcv/v_c4.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_c4.mdl"
SWEP.MovementPoseWalk = 128
SWEP.MovementPoseSprint = 221
SWEP.MovementPoseSighted = 128

SWEP.PlaceKind = "c4"
SWEP.PlacedEntityClass = "mcv_placed_c4"
SWEP.ExplosionDamage = 500
SWEP.ExplosionRadius = 500

SWEP.Primary.Ammo = "mcv_explosive_charge"
SWEP.Primary.ClipSize = -1
SWEP.Primary.DefaultClip = 1

SWEP.WeaponWeight = 5

SWEP.PlacedAngleOffset = Angle(90, 0, 90)
