SWEP.Base = "mcv_base"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_mg43b.txt

// Names and basic information
SWEP.PrintName = "MG43B"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "Nazi Germany"
SWEP.SubCategory = "Light-Machine Guns"
SWEP.Caliber = "7.92x57mm"

SWEP.Slot = 3

SWEP.ViewModel = "models/weapons/mcv/v_mg43b.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_mg43b.mdl"

SWEP.BodyGroups = ""
SWEP.MagInTime = 2.13
SWEP.MagInTimeEmpty = 2.97
SWEP.MagOutTime = 0
SWEP.MagOutTimeEmpty = 0

SWEP.BulletBodygroups = {
    [1] = {1, 1},
    [2] = {2, 1},
    [3] = {3, 1},
    [4] = {4, 1},
    [5] = {5, 1},
    [6] = {6, 1},
    [7] = {7, 1},
    [8] = {8, 1},
    [9] = {9, 1},
    [10] = {10, 1},
    [11] = {11, 1},
    [12] = {12, 1},
    [13] = {13, 1},
    [14] = {14, 1},
    [15] = {15, 1},
    [16] = {16, 1},
}

// Stats

SWEP.DamageGeneric = 50
SWEP.DamageHeadMultiplier = 2
SWEP.DamageChestMultiplier = 0.8
SWEP.DamageStomachMultiplier = 0.75
SWEP.DamageLegMultiplier = 0.55
SWEP.DamageArmMultiplier = 0.5

SWEP.Num = 1

SWEP.RangeModifier = 0.965

SWEP.Firemodes = {
    MCV.FIREMODE_AUTO
}

SWEP.LastShotAnimation = false
SWEP.NoEjectOnShoot = false

// View slide from recoil
SWEP.ViewSlideRecoilUp = 4.2
SWEP.ViewSlideRecoilRight = 2.2

SWEP.ViewSlideRecoilIronsightUp = 3
SWEP.ViewSlideRecoilIronsightRight = 1.6

SWEP.RecoilPushbackValue = 0.5

// Camera shake from recoil
SWEP.ShakeScale = 0.5
SWEP.ShakeFreq = 50
SWEP.ShakeDuration = 0.3

SWEP.Ironsight = true
SWEP.IronsightSpeedScale = 0.4
SWEP.IronsightFov = 90 - 15
SWEP.IronsightWalkBobbingStrength = -0.25
SWEP.MovementPoseWalk = 82
SWEP.MovementPoseSprint = 159
SWEP.MovementPoseSighted = 164

SWEP.HasScope = false
SWEP.ScopeMaterial = NULL
SWEP.ScopeFOV = 8
SWEP.ScopeFOV2 = 4

SWEP.IronsightPos = Vector(0, -10, 0)
SWEP.IronsightAng = Angle(0, 0, 0)

SWEP.CustomPos = Vector(0, 0, 0)
SWEP.CustomAng = Angle(0, 0, 0)

SWEP.Spread = 10.75
SWEP.SpreadIronsighted = 3.5
SWEP.SpreadBipodIronsighted = 2.25

SWEP.FireRate = 800 // in rounds per minute

SWEP.CrosshairMinDistance = 4
SWEP.CrosshairDeltaDistance = 4

SWEP.WeaponWeight = 12

SWEP.Primary.Ammo = "ar2"
SWEP.Primary.ClipSize = 250
SWEP.Primary.Chamber = 0
SWEP.Primary.DefaultClip = 250
SWEP.Primary.Automatic = true

SWEP.NearwallDistance = 45

// Bullet spread multiplier according to current stance
SWEP.CrouchSpreadMultiplier = 0.75
SWEP.ProneSpreadMultiplier = 0.65
SWEP.StandMoveSpreadMultiplier = 1.65
SWEP.SneakMoveSpreadMultiplier = 1.55
SWEP.CrouchMoveSpreadMultiplier = 1.45
SWEP.JumpSpreadMultiplier = 3

SWEP.HasBayonet = false
SWEP.HasRifleGrenade = false

SWEP.BashDamage = 50
SWEP.BayonetDamage = 100

SWEP.HasBipod = true
SWEP.SpreadBipod = 4.25

// Penetration
SWEP.MetalPenetrationDepth = 10
SWEP.GlassPenetrationDepth = 16
SWEP.ConcretePenetrationDepth = 12
SWEP.WoodPenetrationDepth = 20
SWEP.OtherPenetrationDepth = 14

SWEP.MetalDamageModifier = 1.5
SWEP.GlassDamageModifier = 1.1
SWEP.ConcreteDamageModifier = 1.7
SWEP.WoodDamageModifier = 1.2
SWEP.OtherDamageModifier = 1.2

// Sound
SWEP.SoundSingleShot = "MCV_Weapon_MG43.Single"
SWEP.SoundDoubleShot = ""
SWEP.SoundReload = ""
SWEP.SoundReloadThirdPerson = "MCV_Weapon_Foley_ThirdPerson_MG43.Reload"
SWEP.SoundSpecial1 = ""
SWEP.SoundSpecial2 = ""
SWEP.SoundNearlyEmpty = "MCV_Weapon_Generic.NearlyEmptyClick_LMG"
SWEP.SoundEmpty = "MCV_Weapon_Generic.ClipEmpty_01"

// Particles (the game's own systems; particles/*.pcf and their materials ship with the addon)
SWEP.MuzzleParticle = "vietnam_muzzleflash_machinegun_type2_fp"
SWEP.MuzzleParticleSmoke = "vietnam_muzzleflash_machinegun_type1_fp_smoke"
SWEP.MuzzleParticleIronsighted = "vietnam_muzzleflash_machinegun_type2_fp_is"
SWEP.MuzzleParticleIronsightedSmoke = "vietnam_muzzleflash_machinegun_type1_fp_is_smoke"

SWEP.MuzzleParticle3rdPerson = "vietnam_muzzleflash_machinegun_type2_tp"

SWEP.EjectBrassType = 10
SWEP.EjectBrassTrail = "vietnam_weaponeffect_shelleject_trail"
SWEP.EjectBrassParticle = "vietnam_weaponeffect_shelleject_side_mg_m60"

SWEP.TracerParticle = "vietnam_tracer_machinegun_green_primary"
SWEP.TracerParticle2 = "vietnam_tracer_machinegun_green_secondary"

SWEP.TracerRandomness = 6
SWEP.TracerFrequency = 1
