SWEP.Base = "mcv_throwable"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_molotov.txt

// Names and basic information
SWEP.PrintName = "Molotov"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "Finland"
SWEP.SubCategory = "Grenades"

SWEP.Slot = 4

SWEP.ViewModel = "models/weapons/mcv/v_molotov.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_molotov.mdl"
SWEP.MovementPoseWalk = 159
SWEP.MovementPoseSprint = 258
SWEP.MovementPoseSighted = 159

SWEP.ThrowEntity = "mcv_grenade_molotov"
SWEP.FuseImpact = true
SWEP.FuseModes = {0}
SWEP.HasUnderhand = false

SWEP.ExplosionDamage = 35
SWEP.ExplosionRadius = 200

SWEP.Primary.Ammo = "mcv_molotov"
SWEP.Primary.ClipSize = -1
SWEP.Primary.DefaultClip = 1

SWEP.WeaponWeight = 1
