AddCSLuaFile()
SWEP.Base = "mcv_type56"
SWEP.Spawnable = true
SWEP.PrintName = "Type 56 XM148"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.SubCategory = "Assault Rifles"
SWEP.Country = "China"
SWEP.ViewModel = "models/weapons/mcv/v_type56xm148.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_type56xm148.mdl"
SWEP.IconOverride = "entities/mcv_type56xm148.png"
// Unfolded stock: halfway between the folded Type 56-1 and full-stock AK-47.
SWEP.ViewSlideRecoilUp = 1.9
SWEP.ViewSlideRecoilRight = 0.48
SWEP.ViewSlideRecoilIronsightUp = 1.24
SWEP.ViewSlideRecoilIronsightRight = 0.32
SWEP.Spread = 7
SWEP.SpreadIronsighted = 2.25
SWEP.WeaponWeight = 3.7
SWEP.CrouchSpreadMultiplier = 0.75
SWEP.ProneSpreadMultiplier = 0.65
SWEP.StandMoveSpreadMultiplier = 1.3
SWEP.SneakMoveSpreadMultiplier = 1.2
SWEP.CrouchMoveSpreadMultiplier = 1.1
SWEP.JumpSpreadMultiplier = 2.5
SWEP.HasBayonet = false
SWEP.HasRifleGrenade = true
SWEP.RifleGrenadeIsUBGL = true
SWEP.RifleGrenadeEntity = "mcv_proj_40mm"
SWEP.RifleGrenadeForce = 2755
SWEP.SoundGrenadeShot = "MCV_Weapon_M203.Single"
SWEP.Secondary.Ammo = "smg1_grenade"
SWEP.Secondary.ClipSize = 1
SWEP.Secondary.DefaultClip = 1
SWEP.Secondary.Automatic = false
SWEP.MovementPoseWalk = 138
SWEP.MovementPoseSprint = 232
SWEP.MovementPoseSighted = 130
SWEP.SafeMovementAnimations = true
