SWEP.Base = "mcv_placeable"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_m16mine.txt

// Names and basic information
SWEP.PrintName = "M16 Mine"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "United States of America"
SWEP.SubCategory = "Explosives"

SWEP.Slot = 4

SWEP.ViewModel = "models/weapons/mcv/v_mine.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_mine.mdl"
SWEP.MovementPoseWalk = 159
SWEP.MovementPoseSprint = 258
SWEP.MovementPoseSighted = 159
SWEP.BodyGroups = "00"

SWEP.PlaceKind = "mine"
SWEP.PlacedEntityClass = "mcv_placed_mine"
SWEP.ExplosionDamage = 175
SWEP.ExplosionRadius = 250

SWEP.Primary.Ammo = "mcv_mine"
SWEP.Primary.ClipSize = -1
SWEP.Primary.DefaultClip = 1

SWEP.WeaponWeight = 1
