SWEP.Base = "mcv_melee"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_shovel_us.txt

// Names and basic information
SWEP.PrintName = "AMES 1966 Shovel"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "United States of America"
SWEP.SubCategory = "Melee"

SWEP.Slot = 0

SWEP.ViewModel = "models/weapons/mcv/v_shovel_us.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_shovel.mdl"
SWEP.MovementPoseWalk = 167
SWEP.MovementPoseSprint = 268
SWEP.MovementPoseSighted = 167
SWEP.BodyGroups = "0"

SWEP.HoldType = "melee"
SWEP.AimHoldType = "melee"

SWEP.DamageGeneric = 30
SWEP.MeleeRange = 48
SWEP.MeleeRangeAlt = 56
SWEP.SlashRate = 150

SWEP.CanThrow = false

SWEP.SoundHitFlesh = "MCV_Weapon_Shovel.HitFlesh"
SWEP.SoundHitWorld = "MCV_Weapon_Shovel.HitWall"
SWEP.SoundThrustFlesh = "MCV_Weapon_Shovel.HitChargeFlesh"
SWEP.SoundThrustWorld = "MCV_Weapon_Shovel.HitChargeWall"

SWEP.WeaponWeight = 0
