SWEP.Base = "mcv_equipment_box"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_ammobox_us.txt

// Names and basic information
SWEP.PrintName = "Ammunition Box"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = ""
SWEP.SubCategory = "Equipment"

SWEP.Slot = 4

SWEP.ViewModel = "models/weapons/mcv/v_box.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_box.mdl"
SWEP.MovementPoseWalk = 167
SWEP.MovementPoseSprint = 268
SWEP.MovementPoseSighted = 167

SWEP.BoxKind = "ammo"
SWEP.Primary.Ammo = "mcv_ammobox"
SWEP.Primary.ClipSize = -1
SWEP.Primary.DefaultClip = 3
