SWEP.Base = "mcv_base"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_gyrojet_pistol.txt

// Names and basic information
SWEP.PrintName = "Gyrojet Pistol"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "United States of America"
SWEP.SubCategory = "Pistols"
SWEP.Caliber = ".45 ACP"

SWEP.Slot = 1
SWEP.HoldType = "pistol"
SWEP.AimHoldType = "revolver"
SWEP.SprintHoldType = "normal"

SWEP.ViewModel = "models/weapons/mcv/v_gyrojet_pistol.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_gyrojet_pistol.mdl"

SWEP.BodyGroups = ""
SWEP.MagInTime = 0.27
SWEP.MagInTimeEmpty = 0.27
SWEP.MagOutTime = 0
SWEP.MagOutTimeEmpty = 0

// Stats

SWEP.DamageGeneric = 15
SWEP.DamageHeadMultiplier = 7.4
SWEP.DamageChestMultiplier = 5.3
SWEP.DamageStomachMultiplier = 5.2
SWEP.DamageLegMultiplier = 4.1
SWEP.DamageArmMultiplier = 4

SWEP.Num = 1

SWEP.RangeModifier = 0.995

SWEP.Firemodes = {
    MCV.FIREMODE_SEMI
}

SWEP.LastShotAnimation = true
SWEP.ShotgunReload = true
SWEP.InsertClipPoseTime = 0.27
SWEP.ShotgunReloadEmptyStartAnimation = true
SWEP.HasEmptyReload = false
SWEP.NoEjectOnShoot = false

// View slide from recoil
SWEP.ViewSlideRecoilUp = 2.4
SWEP.ViewSlideRecoilRight = 0.4

SWEP.ViewSlideRecoilIronsightUp = 1.44
SWEP.ViewSlideRecoilIronsightRight = 0.24

SWEP.RecoilPushbackValue = 1.5

// Camera shake from recoil
SWEP.ShakeScale = 3
SWEP.ShakeFreq = 30
SWEP.ShakeDuration = 0.4

SWEP.Ironsight = true
SWEP.IronsightSpeedScale = 1
SWEP.IronsightFov = 90 - 15
SWEP.IronsightWalkBobbingStrength = -0.25
SWEP.MovementPoseWalk = 157
SWEP.MovementPoseSprint = 255
SWEP.MovementPoseSighted = 130

SWEP.HasScope = false
SWEP.ScopeMaterial = NULL
SWEP.ScopeFOV = 8
SWEP.ScopeFOV2 = 4

SWEP.IronsightPos = Vector(-0.02, -4, 0)
SWEP.IronsightAng = Angle(0, 0, 0)

SWEP.CustomPos = Vector(0, 0, 0)
SWEP.CustomAng = Angle(0, 0, 0)

SWEP.Spread = 9
SWEP.SpreadIronsighted = 3

SWEP.FireRate = 200 // in rounds per minute

SWEP.CrosshairMinDistance = 6
SWEP.CrosshairDeltaDistance = 8

SWEP.WeaponWeight = 0.6

SWEP.Primary.Ammo = "pistol"
SWEP.Primary.ClipSize = 6
SWEP.Primary.Chamber = 0
SWEP.Primary.DefaultClip = 6
SWEP.Primary.Automatic = true

SWEP.NearwallDistance = 25

// Bullet spread multiplier according to current stance
SWEP.CrouchSpreadMultiplier = 0.8
SWEP.ProneSpreadMultiplier = 0.75
SWEP.StandMoveSpreadMultiplier = 1.2
SWEP.SneakMoveSpreadMultiplier = 1.1
SWEP.CrouchMoveSpreadMultiplier = 1.15
SWEP.JumpSpreadMultiplier = 1.35

SWEP.HasBayonet = false
SWEP.HasRifleGrenade = false

SWEP.BashDamage = 50
SWEP.BayonetDamage = 100

SWEP.HasBipod = false

// Penetration
SWEP.MetalPenetrationDepth = 3
SWEP.GlassPenetrationDepth = 6
SWEP.ConcretePenetrationDepth = 4
SWEP.WoodPenetrationDepth = 8
SWEP.OtherPenetrationDepth = 5

SWEP.MetalDamageModifier = 1.8
SWEP.GlassDamageModifier = 1.4
SWEP.ConcreteDamageModifier = 2
SWEP.WoodDamageModifier = 1.5
SWEP.OtherDamageModifier = 1.5

// Sound
SWEP.SoundSingleShot = "MCV_Weapon_Gyrojet_Pistol.Single"
SWEP.SoundDoubleShot = ""
SWEP.SoundReload = ""
SWEP.SoundReloadLoopThirdPerson = "MCV_Weapon_Foley_ThirdPerson_Gyrojet_Pistol.ReloadLoop"
SWEP.SoundCycleThirdPerson = "MCV_Weapon_Foley_ThirdPerson_Gyrojet_Pistol.Cycle"
SWEP.SoundSpecial1 = ""
SWEP.SoundSpecial2 = ""
SWEP.SoundNearlyEmpty = "MCV_Weapon_Generic.NearlyEmptyClick"
SWEP.SoundEmpty = "MCV_Weapon_Generic.ClipEmpty_08"

// Particles (the game's own systems; particles/*.pcf and their materials ship with the addon)
SWEP.MuzzleParticle = "vietnam_muzzleflash_pistol_gyrojet_fp"
SWEP.MuzzleParticleSmoke = "vietnam_muzzleflash_pistol_gyrojet_fp_smoke"
SWEP.MuzzleParticleIronsighted = "vietnam_muzzleflash_pistol_gyrojet_fp_is"
SWEP.MuzzleParticleIronsightedSmoke = "vietnam_muzzleflash_pistol_gyrojet_fp_is_smoke"

SWEP.MuzzleParticle3rdPerson = "vietnam_muzzleflash_pistol_gyrojet_tp"

SWEP.EjectBrassType = 0
SWEP.EjectBrassTrail = ""
SWEP.EjectBrassParticle = ""

SWEP.TracerParticle = "vietnam_tracer_gyrojet_primary"
SWEP.TracerParticle2 = "vietnam_tracer_gyrojet_secondary"

SWEP.TracerRandomness = 6
SWEP.TracerFrequency = 1
