SWEP.Base = "mcv_throwable"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_m6a1.txt

// Names and basic information
SWEP.PrintName = "M6A1 Gas"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "United States of America"
SWEP.SubCategory = "Grenades"

SWEP.Slot = 4

SWEP.ViewModel = "models/weapons/mcv/v_m18.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_m18.mdl"
SWEP.MovementPoseWalk = 159
SWEP.MovementPoseSprint = 258
SWEP.MovementPoseSighted = 159

SWEP.ThrowEntity = "mcv_grenade_gas"
SWEP.FuseModes = {2.5, 5}
SWEP.HasUnderhand = true

SWEP.ExplosionDamage = 20
SWEP.ExplosionRadius = 500

SWEP.Primary.Ammo = "mcv_grenade"
SWEP.Primary.ClipSize = -1
SWEP.Primary.DefaultClip = 2

SWEP.WeaponWeight = 1
