SWEP.Base = "mcv_base"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_mk22_mod0.txt

// Names and basic information
SWEP.PrintName = "Mk 22 Mod 0"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "United States of America"
SWEP.SubCategory = "Pistols"
SWEP.Caliber = "9x19mm"

SWEP.Slot = 1
SWEP.HoldType = "pistol"
SWEP.AimHoldType = "revolver"
SWEP.SprintHoldType = "normal"

SWEP.ViewModel = "models/weapons/mcv/v_mk22.mdl"
// The dual suppressors are a separate model, not the single gun's variant bodygroup.
SWEP.ViewModelAkimbo = "models/weapons/mcv/v_dual_mk22_mod0.mdl"
SWEP.AkimboPoseRecoil = true
SWEP.WorldModel = "models/weapons/mcv/w_mk22.mdl"

SWEP.BodyGroups = "01"
SWEP.WorldModelBodyGroups = "01"

// When the reload animation swaps the magazine / belt (from its events): the rounds shown
// on the model switch from the old count to the new one here, 0 in between when it is out
SWEP.MagInTime = 1.07
SWEP.MagInTimeEmpty = 1.07
SWEP.MagOutTime = 0
SWEP.MagOutTimeEmpty = 0

// Stats

SWEP.DamageGeneric = 25
SWEP.DamageHeadMultiplier = 3.6
SWEP.DamageChestMultiplier = 1.9
SWEP.DamageStomachMultiplier = 1.85
SWEP.DamageLegMultiplier = 1.2
SWEP.DamageArmMultiplier = 1.15

SWEP.Num = 1

SWEP.RangeModifier = 0.745

SWEP.Firemodes = {
    MCV.FIREMODE_SEMI
}

SWEP.LastShotAnimation = true
SWEP.NoEjectOnShoot = false

// View slide from recoil
SWEP.ViewSlideRecoilUp = 1.2
SWEP.ViewSlideRecoilRight = 0.48

SWEP.ViewSlideRecoilIronsightUp = 1
SWEP.ViewSlideRecoilIronsightRight = 0.4

SWEP.RecoilPushbackValue = 1.5

// Camera shake from recoil
SWEP.ShakeScale = 0.75
SWEP.ShakeFreq = 50
SWEP.ShakeDuration = 0.3

SWEP.Ironsight = true
SWEP.IronsightSpeedScale = 0.85
SWEP.IronsightFov = 90 - 15
SWEP.IronsightWalkBobbingStrength = -1
SWEP.MovementPoseWalk = 161
SWEP.MovementPoseSprint = 260
SWEP.MovementPoseSighted = 130

SWEP.HasScope = false
SWEP.ScopeMaterial = NULL
SWEP.ScopeFOV = 8
SWEP.ScopeFOV2 = 4

SWEP.IronsightPos = Vector(-0, -5, -0.475)
SWEP.IronsightAng = Angle(0, 0.05, 0)
SWEP.IronsightPosAkimbo = Vector(0.25, -5, -0.45)
SWEP.IronsightAngAkimbo = Angle(0, 0, 0)

SWEP.CustomPos = Vector(0, -3, 0)
SWEP.CustomAng = Angle(0, 0, 0)

SWEP.Spread = 6
SWEP.SpreadIronsighted = 2

SWEP.FireRate = 540 // in rounds per minute

SWEP.CrosshairMinDistance = 4
SWEP.CrosshairDeltaDistance = 4

SWEP.WeaponWeight = 0.952

SWEP.Primary.Ammo = "pistol"
SWEP.Primary.ClipSize = 8
SWEP.Primary.Chamber = 1
SWEP.Primary.DefaultClip = 24
SWEP.Primary.Automatic = true

SWEP.NearwallDistance = 26

// Bullet spread multiplier according to current stance
SWEP.CrouchSpreadMultiplier = 0.95
SWEP.ProneSpreadMultiplier = 0.9
SWEP.StandMoveSpreadMultiplier = 1.1
SWEP.SneakMoveSpreadMultiplier = 1.05
SWEP.CrouchMoveSpreadMultiplier = 1
SWEP.JumpSpreadMultiplier = 1.25

SWEP.HasBayonet = false
SWEP.HasRifleGrenade = false
SWEP.HasAkimbo = true

SWEP.BashDamage = 50
SWEP.BayonetDamage = 100

SWEP.HasBipod = false

// Penetration
SWEP.MetalPenetrationDepth = 5
SWEP.GlassPenetrationDepth = 11
SWEP.ConcretePenetrationDepth = 7
SWEP.WoodPenetrationDepth = 15
SWEP.OtherPenetrationDepth = 9

SWEP.MetalDamageModifier = 1.7
SWEP.GlassDamageModifier = 1.3
SWEP.ConcreteDamageModifier = 1.9
SWEP.WoodDamageModifier = 1.4
SWEP.OtherDamageModifier = 1.4

// Sound
SWEP.SoundSingleShot = "MCV_Weapon_MK22_MOD0.Single"
SWEP.SoundDoubleShot = ""
SWEP.SoundReload = ""
SWEP.SoundReloadThirdPerson = "MCV_Weapon_Foley_ThirdPerson_MK22.Reload"
SWEP.SoundSpecial1 = ""
SWEP.SoundSpecial2 = ""
SWEP.SoundNearlyEmpty = "MCV_Weapon_Generic.NearlyEmptyClick_Pistol"
SWEP.SoundEmpty = "MCV_Weapon_Generic.ClipEmpty_03"

// Particles (the game's own systems; particles/*.pcf and their materials ship with the addon)
SWEP.MuzzleParticle = "vietnam_muzzleflash_pistol_type2_fp"
SWEP.MuzzleParticleSmoke = "vietnam_muzzleflash_pistol_type2_fp_smoke"
SWEP.MuzzleParticleIronsighted = "vietnam_muzzleflash_pistol_type2_fp_is"
SWEP.MuzzleParticleIronsightedSmoke = "vietnam_muzzleflash_pistol_type2_fp_is_smoke"

SWEP.MuzzleParticle3rdPerson = "vietnam_muzzleflash_pistol_type2_tp"

SWEP.EjectBrassType = 12
SWEP.EjectBrassTrail = "vietnam_weaponeffect_shelleject_trail"
SWEP.EjectBrassParticle = "vietnam_weaponeffect_shelleject_side"

SWEP.TracerParticle = ""
SWEP.TracerParticle2 = ""

SWEP.TracerRandomness = 4
SWEP.TracerFrequency = 1
