SWEP.Base = "mcv_equipment_box"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_medicbox_us.txt

// Names and basic information
SWEP.PrintName = "Medical Kit"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = ""
SWEP.SubCategory = "Equipment"

SWEP.Slot = 4

SWEP.ViewModel = "models/weapons/mcv/v_medicbox.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_medicbox.mdl"
SWEP.MovementPoseWalk = 167
SWEP.MovementPoseSprint = 268
SWEP.MovementPoseSighted = 167

SWEP.BoxKind = "medic"
SWEP.Primary.Ammo = "mcv_medicbox"
SWEP.Primary.ClipSize = -1
SWEP.Primary.DefaultClip = 3
