SWEP.Base = "mcv_melee"
SWEP.IsBayonet = true // carrying it lets the rifles fix their bayonet

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_m7_bayonet.txt

// Names and basic information
SWEP.PrintName = "M7 Bayonet"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "United States of America"
SWEP.SubCategory = "Melee"

SWEP.Slot = 0

SWEP.ViewModel = "models/weapons/mcv/v_m7_bayonet.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_m7_bayonet.mdl"
SWEP.MovementPoseWalk = 167
SWEP.MovementPoseSprint = 268
SWEP.MovementPoseSighted = 167


SWEP.DamageGeneric = 35
SWEP.DamageGenericAlt = 55
SWEP.MeleeRange = 32
SWEP.MeleeRangeAlt = 48
SWEP.SlashRate = 150

SWEP.CanThrow = true

SWEP.SoundHitFlesh = "MCV_Weapon_M7_Bayonet.Stab"
SWEP.SoundHitWorld = "MCV_Weapon_M7_Bayonet.Hit"
SWEP.SoundThrustFlesh = "MCV_Weapon_M7_Bayonet.ThrustStab"
SWEP.SoundThrustWorld = "MCV_Weapon_M7_Bayonet.ThrustHit"

SWEP.WeaponWeight = 0
