SWEP.Base = "mcv_binoculars"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_binoculars_us.txt

// Names and basic information
SWEP.PrintName = "Binoculars"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = ""
SWEP.SubCategory = "Equipment"

SWEP.Slot = 4

SWEP.ViewModel = "models/weapons/mcv/v_binocular.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_binocular.mdl"
SWEP.MovementPoseWalk = 158
SWEP.MovementPoseSprint = 258
SWEP.MovementPoseSighted = 130
SWEP.CustomPos = Vector(0, 0, 0)
SWEP.CustomAng = Angle(0, 0, 0)

SWEP.IronsightPos = Vector(0, 0, 0)
SWEP.IronsightAng = Angle(0, 0, 0) -- TODO tune
