SWEP.Base = "mcv_throwable"

SWEP.Spawnable = true

AddCSLuaFile()

// Generated by work/port_weapon.py from cscripts/weapon_stielhand_explosive.txt

// Names and basic information
SWEP.PrintName = "Stielhandgranate"
SWEP.Category = "Military Conflict: Vietnam"
SWEP.Country = "Nazi Germany"
SWEP.SubCategory = "Grenades"

SWEP.Slot = 4

SWEP.ViewModel = "models/weapons/mcv/v_stielhandgranate.mdl"
SWEP.WorldModel = "models/weapons/mcv/w_stielhandgranate.mdl"

SWEP.ThrowEntity = "mcv_grenade_frag"
SWEP.FuseModes = {3, 5}
SWEP.HasUnderhand = true

SWEP.ExplosionDamage = 140
SWEP.ExplosionRadius = 350

SWEP.Primary.Ammo = "mcv_grenade"
SWEP.Primary.ClipSize = -1
SWEP.Primary.DefaultClip = 2

SWEP.WeaponWeight = 1
